services:
  starscream:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHROMA_URL=http://chroma:8000
    volumes:
      - ./contents:/contents
      - starscream_data:/app/data
    restart: unless-stopped
    depends_on:
      - chroma
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  starscream-dev:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    depends_on:
      - chroma
      - chromadb-admin
    environment:
      - NODE_ENV=development
      - CHROMA_URL=http://chroma:8000
    volumes:
      - .:/app
      # - /app/node_modules
    command: [ "bun", "run", "--hot", "src/index.ts" ]
    profiles:
      - dev

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_CORS_ALLOW_ORIGINS=["*"]
    ports:
      - "8000:8000"
    restart: unless-stopped

  chromadb-admin:
    image: fengzhichao/chromadb-admin
    ports:
      - "3001:3001"
    depends_on:
      - chroma
    restart: unless-stopped
    environment:
      - CHROMA_SERVER_URL=http://chroma:8000

volumes:
  starscream_data:
  chroma_data:


